name: Build and deploy docs
on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Git repository
        uses: actions/checkout@v2
      
      - name: Install dependencies
        run: yarn && cd docs && yarn
      
      - name: Build the plugin
        run: cd docs && yarn build

      - name: Build and Deploy
        uses: jenkey2011/vuepress-deploy@master
        env:
          # See https://github.com/marketplace/actions/vuepress-deploy#create-a-personal-access-token
          # on how to create and store an access token in case a new one is
          # ever needed
          ACCESS_TOKEN: ${{ secrets.ACCESS_TOKEN }}
          TARGET_BRANCH: docs
          BUILD_SCRIPT: yarn build
          BUILD_DIR: docs/src/.vuepress/dist
